FROM amd64/amazoncorretto:17

WORKDIR /app

COPY ./build/libs/SeeYouAgain-Batch-0.0.1-SNAPSHOT.jar /app/seeyouagain.jar

CMD ["java", "-Duser.timezone=Asia/Seoul", "-jar", "-Dspring.profiles.active=dev", "seeyouagain.jar"]